### ISSUE TITLE
Only cookies being sent?

### ISSUE THREAD

**Issue by Genus-learner** [darkarp/chromepass#36] opened 2021-05-17 05:30 UTC
So I got it working on multiple computers
but for some of them they client only sends cookies?
I've tried running it as admin and that hasnt done anything to help that

Any suggestions?

**Comment by darkarp** [comment] 2021-05-18 08:58
I'll look into this. Unfortunately I don't have much time right now but I'll try to check it out as soon as possible. 

A couple of things,
1. Are you sure that the browser has saved passwords?
2. Perhaps the browser installation didn't occur at the default location?

**Comment by Genus-learner** [comment] 2021-05-18 09:49
> I'll look into this. Unfortunately I don't have much time right now but I'll try to check it out as soon as possible.
> 
> A couple of things,
> 
> 1. Are you sure that the browser has saved passwords?
> 2. Perhaps the browser installation didn't occur at the default location?

1.) Yeah, I think so. it does has autofill passwords and a login file in:
C:\Users\Username\AppData\Local\Google\Chrome\User Data\Default

2.) Pretty sure its at the default location:
C:\Program Files (x86)\Google\Chrome\Application

**Comment by darkarp** [comment] 2021-05-18 09:50
Interesting. It is probably a bug, thanks for reporting it. I'll try to figure it out as soon as I have a better availability!

**Comment by darkarp** [comment] 2021-05-18 09:52
Perhaps the bug isn't in acquiring the data itself but handling it on the server side, since the cookies are correctly sent.

**Comment by Genus-learner** [comment] 2021-05-18 10:03
It's very peculiar since it got it to give both cookies and login data on 3 different computers
But not on two others. I suspected some sort of permissions issue, but you guess it could be server side?
Hard to say but the console gives 4 html notifications (probably not the correct name I'm not good at this stuff) for each file/data its receiving and it only gives 1 line for these 2 computers.

**Comment by darkarp** [comment] 2021-05-24 18:16
That's definitely strange. The only way that would usually happen is if they were empty.
The error should either be in opening the file, or the server parsing it. I apologize for not having the time to try to reproduce it yet.

**Comment by darkarp** [comment] 2021-08-12 20:26
A new version with a reworked server has been pushed, so I'll close this for now. If the problem still happens please open another issue. Thanks :D

**Closed by darkarp** 2021-08-12 20:26 UTC
Labels: bug, In progress
