### ISSUE TITLE
Build to exe faild

### ISSUE THREAD

**Issue by sparta34** [darkarp/chromepass#20] opened 2019-11-05 16:09 UTC
when i try to build the client to .exe it gives me these errors Traceback (most recent call last):
  File "c:\users\defender\appdata\local\programs\python\python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\defender\appdata\local\programs\python\python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\defender\AppData\Local\Programs\Python\Python37-32\Scripts\build_exe.exe\__main__.py", line 7, in <module>
  File "c:\users\defender\appdata\local\programs\python\python37-32\lib\site-packages\py2exe\build_exe.py", line 141, in main
    builder.analyze()
  File "c:\users\defender\appdata\local\programs\python\python37-32\lib\site-packages\py2exe\runtime.py", line 160, in analyze
    self.mf.import_hook(modname)
  File "c:\users\defender\appdata\local\programs\python\python37-32\lib\site-packages\py2exe\mf3.py", line 120, in import_hook
    module = self._gcd_import(name)
  File "c:\users\defender\appdata\local\programs\python\python37-32\lib\site-packages\py2exe\mf3.py", line 274, in _gcd_import
    return self._find_and_load(name)
  File "c:\users\defender\appdata\local\programs\python\python37-32\lib\site-packages\py2exe\mf3.py", line 357, in _find_and_load
    self._scan_code(module.__code__, module)
  File "c:\users\defender\appdata\local\programs\python\python37-32\lib\site-packages\py2exe\mf3.py", line 388, in _scan_code
    for what, args in self._scan_opcodes(code):
  File "c:\users\defender\appdata\local\programs\python\python37-32\lib\site-packages\py2exe\mf3.py", line 417, in _scan_opcodes
    yield "store", (names[oparg],)
IndexError: tuple index out of range

i'm using 
 - OS: [e.g. Windows 10 Pro x64]
 - Python Version [3.7.1]
 - Python Environment Normal python

**Comment by darkarp** [comment] 2019-11-06 15:02
will take a look

**Comment by sparta34** [comment] 2019-11-06 16:55
ok thanks

**Comment by Rorzhak** [comment] 2019-11-12 01:31
I have the same problem

**Comment by darkarp** [comment] 2019-11-14 17:11
Can't reproduce that problem specifically. Could you try to do it inside of a conda environment with python 3.7.1?

**Comment by sergiogalvan** [comment] 2019-11-29 21:06
Great work!, I tried in mini anaconda enviroment 64 bits, seems to work well.
I compiled option 1 (email) with my gmail data, but when compiled brings an error. Log is:

Traceback (most recent call last):
  File "server.py", line 105, in <module>
  File "server.py", line 82, in sendpass
FileNotFoundError: [Errno 2] No such file or directory: 'error.txt'

Is part of the issue you are working on?

And when compiling reverseserver option, compilation goes well but on shell shows:
(not exactly but something like this:) "WinError3 - System couldn't find specified route ''."
It happends after this line:
Copy DLL C:\Miniconda\Library\bin\sqlite3.dll to dist

Is this normal, something I'm doing wrong? I didn't test if it's working yet.

**Comment by darkarp** [comment] 2019-11-30 12:05
Yes I’m working on that error, indirectly. Very soon, there will be a complete update. It will have many more features and it will be done in a very different and cleaner way. That won’t be an issue anymore as well.

**Comment by darkarp** [comment] 2019-11-30 12:11
Also, the email shouldn’t be working at the moment. The reason being that gmail has a problem I’m addressing. The problem you’re facing shouldn’t actually exist at the moment. I will look at it again just to be sure. I never tried it in a miniconda environment, only on a full anaconda one.

**Comment by darkarp** [comment] 2019-11-30 12:12
If there’s a small problem I can easily fix on the current version I’ll do that. Otherwise, I think it would just be best to work on the updated version that won’t have that problem at all.

**Comment by sergiogalvan** [comment] 2019-11-30 14:34
Hello, thanks for quick reply! Ok I'll try on full anaconda enviroment as well.. 
Maybe Gmail issue is something related to less secure apps and smpt manual activation maybe needed on gmail?

May we try with zoho mail for example? smtp.zoho.com, 587 port. Is just change the smtp server data on the code right?

I hope you can fix and wait for your updated version as well to try it!

**Comment by darkarp** [comment] 2019-11-30 17:57
No problem! Yeah that’s the problem exactly. I used to do it with gmx but now they don’t allow all access from many unknown ips. I don’t know Zoho but it could work. I’d love if you could tell me if it worked well afterwards. I can add it on the next version as an option as well :)

**Comment by darkarp** [comment] 2019-11-30 21:40
(I can comfortably say the ETA for the new version is 7 days, completed with the features outlined in the Todo section)

**Comment by sergiogalvan** [comment] 2019-12-03 04:46
Yes please, add ZOHO MAIL and I'll let you know if it works!
ZOHO also need manual smtp activation, but no problem with "less secure apps" at least on paid accounts. Maybe you can give the option to set server/port customized.
Great to hear 7 days to go! Best of luck! Anxious to test!

**Comment by darkarp** [comment] 2019-12-03 10:35
I will close this issue for now as I add the new features to the next version.
Meanwhile, I will upload the next version today, in a few hours, still in alpha testing.

I will upload it in a new repo because it isn't just chrome password stealing anymore, but that is a feature that is already working. 

It will be further explained in the wiki.

The new repo is: https://github.com/darkarp/malkit

**Closed by darkarp** 2019-12-03 10:35 UTC
Labels: In progress
